<a href="https://colab.research.google.com/github/BriacLEGUILLOU/Impact_score/blob/master/Impact_score_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importation des données

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
pd.set_option('display.max_rows', 60)

In [ ]:
def obtention_exp10(nb):
  """ Permet de convertir un nombre de la façon suivante :
  1e6 -> 6
  - 1e6 -> -6 """
  signe = np.sign(nb)
  nb = np.absolute(nb)
  if nb == 0:
    return 0
  else :
    return math.exp(nb * math.log(10)) * signe
  
obtention_exp10(6)

1000000.0000000013

In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount("/content/gdrive")

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
# Chargement des données
# L'utilisateur peut sélectionner la catégories APE souhaitée
# Il est nécessaire d'avoir accès au dossier 'Export données par catégorie' de Briac
ape_cat0 = '03'
data_log10 = pd.read_excel('/content/gdrive/My Drive/Impact Score/Export données par catégorie/data{}.xlsx'.format(ape_cat0), index_col=0) # donnée logarithmic
data = pd.concat([data_log10.iloc[:,0],data_log10.iloc[:,1:69].applymap(obtention_exp10), data_log10.iloc[:,69:-1]], axis=1) # donnée réelle

# Réalisation de graphiques

In [ ]:
data

         year  Autres impôts, taxes et versements assimilés  ...  ape_cat2  ape_cat3
6570     2013                                           NaN  ...         2         Z
6571     2014                                           NaN  ...         2         Z
6572     2015                                           NaN  ...         2         Z
6573     2016                                           NaN  ...         2         Z
6574     2017                                           NaN  ...         2         Z
...       ...                                           ...  ...       ...       ...
1263954  2018                                           NaN  ...         1         Z
1263988  2018                                           NaN  ...         1         Z
1270288  2018                                           NaN  ...         1         Z
1271118  2019                                           NaN  ...         1         Z
1272131  2019                                           NaN  ...         1         Z

[679 rows x 82 columns]